import chrustus from '../../assets/img/chrystusSwJanaDali.jpg';
import chrustusMin from '../../assets/img/min/chrystusSwJanaDali.jpg';
import zonkile from '../../assets/img/zonkile.jpg';
import zonkileMin from '../../assets/img/min/zonkile.jpg';
import gory from '../../assets/img/gory.jpg';
import goryMin from '../../assets/img/min/gory.jpg';
import largeOfficeBuilding from '../../assets/img/large-office-building.jpg';
import largeOfficeBuildingMin from '../../assets/img/min/large-office-building.jpg';
import sedanParkedAtAdesertedAreaUnderAcloudySky
  from '../../assets/img/sedan-parked-at-a-deserted-area-under-a-cloudy-sky.jpg';
import sedanParkedAtAdesertedAreaUnderAcloudySkyMin
  from '../../assets/img/min/sedan-parked-at-a-deserted-area-under-a-cloudy-sky.jpg';
import jimMorrison from '../../assets/img/jim-morrison.jpg';
import jimMorrisonMin from '../../assets/img/min/jim-morrison.jpg';
import goryMt from '../../assets/img/gory-mt.jpg';
import goryMtMin from '../../assets/img/min/gory-mt.jpg';
import biblioteczka from '../../assets/img/biblioteczka.jpg';
import biblioteczkaMin from '../../assets/img/min/biblioteczka.jpg';
import transcendencji from '../../assets/img/w-poszukiwaniu-transcendencji.jpg';
import transcendencjiMin from '../../assets/img/min/w-poszukiwaniu-transcendencji.jpg';
import wielkaCisza from '../../assets/img/wielka-cisza.jpg';
import wielkaCiszaMin from '../../assets/img/min/wielka-cisza.jpg';

const data = [
  {
    id: 1,
    title: "Biblijna Droga Krzyżowa",
    text: [
      "Rozważania przygotowane przeze mnie dla Duszpasterstwa Młodzieży przy Bazylice Ojców Karmelitów Na Piasku i wraz z prezentacją zostały wykorzystane do Nabożeństwa Biblijnej Drogi Krzyżowej 12.04.2019",
      "### **Wstęp**",
      "Z Ewangelii Św. Jana:\n *Niech się nie trwoży serce wasze. Wierzycie w Boga? I we Mnie wierzcie! W domu Ojca mego jest mieszkań wiele. Gdyby tak nie było, to bym wam powiedział. Idę przecież przygotować wam miejsce. A gdy odejdę i przygotuję wam miejsce, przyjdę powtórnie i zabiorę was do siebie, abyście i wy byli tam, gdzie Ja jestem. Znacie drogę, dokąd Ja idę». Odezwał się do Niego Tomasz: «Panie, nie wiemy, dokąd idziesz. Jak więc możemy znać drogę?» Odpowiedział mu Jezus: «Ja jestem drogą i prawdą, i życiem. Nikt nie przychodzi do Ojca inaczej jak tylko przeze Mnie.* \n Zapraszamy do medytacji czternastu scen z drogi krzyżowej Jezusa, opisanych okiem Ewangelistów. Niech staną się one dla nas inspiracją do poszukiwania prawdy i kroczenia drogą, która zaprowadzi nas do pełni Życia, którym jest Chrystus.",
      "### **Stacja 1 Jezus w Ogrodzie Oliwnym**",
      "**Kłaniamy Ci się Panie Jezu Chryste i błogosławimy Tobie, żeś przez krzyż i mękę swoją świat odkupić raczył.**",
      "Z Ewangelii Św. Mateusza:\n *Wtedy przyszedł Jezus z nimi do ogrodu, zwanego Getsemani, i rzekł do uczniów: «Usiądźcie tu, Ja tymczasem odejdę tam i będę się modlił». Wziąwszy z sobą Piotra i dwóch synów Zebedeusza, począł się smucić i odczuwać trwogę. Wtedy rzekł do nich: «Smutna jest moja dusza aż do śmierci; zostańcie tu i czuwajcie ze Mną!» I odszedłszy nieco dalej, upadł na twarz i modlił się tymi słowami: «Ojcze mój, jeśli to możliwe, niech Mnie ominie ten kielich! Wszakże nie jak Ja chcę, ale jak Ty»*\n Trudna i szczera jest ta rozmowa Jezusa z Ojcem, bo i cała sytuacja nie należy do łatwych: za chwilę czeka go haniebna śmierć. Jednak przyznanie się do swoich rozterek jest pierwszym krokiem do wkroczenia na drogę krzyża. Jezus swojej siły upatruje nie we własnej osobie, nie we własnym ciele i możliwościach, ale w osobie Ojca. Ten scenariusz powtarza się przed każdym z ważnych wydarzeń z życia naszego Mistrza: po pierwsze modlitwa.",
      "Jezu, naucz mnie wszystko zaczynać od modlitwy.",
      "### **Stacja 2 Jezus zdradzony przez Judasza**",
      "**Kłaniamy Ci się Panie Jezu Chryste i błogosławimy Tobie, żeś przez krzyż i mękę swoją świat odkupić raczył.**",
      "Z Ewangelii Św. Mateusza:\n *Gdy On jeszcze mówił, oto nadszedł Judasz, jeden z Dwunastu, a z nim wielka zgraja z mieczami i kijami, od arcykapłanów i starszych ludu. Zdrajca zaś dał im taki znak: «Ten, którego pocałuję, to On; Jego pochwyćcie!». Zaraz też przystąpił do Jezusa, mówiąc: «Witaj Rabbi!», i pocałował Go. A Jezus rzekł do niego: «Przyjacielu, po coś przyszedł?»* Przyjacielu… nie zdrajco, nikczemniku, sprzedawczyku, tylko właśnie przyjacielu /towarzyszu - tak Jezus zwraca się do tego, który go wydał. W Jezusie nie ma pretensji o zdradę. Patrzy on na Judasza przez pryzmat konkretnej osoby, człowieka, którego zna a nie czynów i wydarzeń, które ten sprokurował. Zdrady nie są niezwykłe, są powszechne, także dzisiaj – przywołaj w pamięci jedną z nich. Czy reakcje osób zdradzonych są takie jak reakcja Jezusa…?",
      "Jezu, naucz mnie w grzesznej osobie zawsze widzieć człowieka.",
      "### **Stacja 3 Jezus skazany przez Sanhedryn**",
      "**Kłaniamy Ci się Panie Jezu Chryste i błogosławimy Tobie, żeś przez krzyż i mękę swoją świat odkupić raczył.**",
      "Z Ewangelii Św. Jana: \n *Wówczas jeden z nich, Kajfasz, który w owym roku był najwyższym kapłanem, rzekł do nich: «Wy nic nie rozumiecie i nie bierzecie tego pod uwagę, że lepiej jest dla was, gdy jeden człowiek umrze za lud, niż miałby zginąć cały naród». Tego jednak nie powiedział sam od siebie, ale jako najwyższy kapłan w owym roku wypowiedział proroctwo, że Jezus miał umrzeć za naród, a nie tylko za naród, ale także, by rozproszone dzieci Boże zgromadzić w jedno. Tego więc dnia postanowili Go zabić.* \n Wyrok zapada tutaj jeszcze zanim zaczęła się właściwa rozprawa. Bo nie ważna była prawda i osoba, o Bogu nie wspominając, lecz interesy i droga korzyści. Czysty pragmatyzm. Winny- niewinny, kogo to obchodzi – zginie wszystkim będzie lepiej. A tytuł winy? Nieważne – daj mi człowieka to znajdę Ci paragraf. A Jezus dalej robił to, co do Niego należało. Rozmyta odpowiedzialność, kult stanowisk, patrzenie na sytuacje poprzez pryzmat zysków… Znasz to skądś? Ja znam… Z nagłówków gazet, wydarzeń w szkole, na uczelni, sytuacji w pracy, rodzinie, wspólnocie…",
      "Jezu, naucz mnie by w moim życiu to człowiek się liczył a nie interesy.",
      "### **Stacja 4 Piotr wypiera się Jezusa**",
      "**Kłaniamy Ci się Panie Jezu Chryste i błogosławimy Tobie, żeś przez krzyż i mękę swoją świat odkupić raczył.**",
      "Z Ewangelii Św. Łukasza: \n *Gdy rozniecili ogień na środku dziedzińca i zasiedli wkoło, Piotr usiadł także między nimi. A jakaś służąca, zobaczywszy go siedzącego przy ogniu, przyjrzała mu się uważnie i rzekła: «I ten był razem z Nim». Lecz on zaprzeczył temu, mówiąc: «Nie znam Go, kobieto». Po chwili zobaczył go ktoś inny i rzekł: «I ty jesteś jednym z nich». Piotr odrzekł: «Człowieku, nie jestem». Po upływie prawie godziny jeszcze ktoś inny począł zawzięcie twierdzić: «Na pewno i ten był razem z Nim; jest przecież Galilejczykiem». Piotr zaś rzekł: «Człowieku, nie wiem, co mówisz». I w tej chwili, gdy on jeszcze mówił, kogut zapiał. A Pan obrócił się i spojrzał na Piotra. Wspomniał Piotr na słowo Pana, jak mu powiedział: «Dziś, zanim kogut zapieje, trzy razy się Mnie wyprzesz». Wyszedł na zewnątrz i gorzko zapłakał.* \n Trzykrotne „nie znam Go” to już chyba nie przypadek. Jezus został sam, wyparł się go nawet Piotr - ten który przecież miał być skałą. Można w takiej chwili zwątpić. Można zareagować tak, że ostatecznie pogrzebiemy tego, który się nas wyparł. Ale nie taka jest reakcja Boga, bo jak mówi św. Paweł Jeśli my odmawiamy wierności, On wiary dochowuje, bo nie może się zaprzeć siebie samego. Jak miłosierne i wychowujące musiało być zatem spojrzenie Jezusa, że Piotr po potrójnym wyparciu się nie uciekł swoim wzrokiem od Jego wzroku, tylko pozwolił mu się nim przeniknąć? Jak ucząca musiała być to lekcja, że w ostatecznym rozrachunku Piotr podąży za Panem i tak jak On poniesie śmierć krzyżową?",
      "Jezu, naucz mnie by szukać Twojego miłosiernego spojrzenia i w jego świetle uznawać moje słabości.",
      "### **Stacja 5 Jezus sądzony przez Piłata**",
      "**Kłaniamy Ci się Panie Jezu Chryste i błogosławimy Tobie, żeś przez krzyż i mękę swoją świat odkupić raczył.**",
      "Z Ewangelii Św. Jana:\n *Rzekł więc Piłat do Niego: «Nie chcesz mówić ze mną? Czy nie wiesz, że mam władzę uwolnić Ciebie i mam władzą Ciebie ukrzyżować?» Jezus odpowiedział: «Nie miałbyś żadnej władzy nade Mną, gdyby ci jej nie dano z góry. Dlatego większy grzech ma ten, który Mnie wydał tobie». Odtąd Piłat usiłował Go uwolnić. Żydzi jednak zawołali: «Jeżeli Go uwolnisz, nie jesteś przyjacielem Cezara.(…) Piłat rzekł do nich: «Czyż króla waszego mam ukrzyżować?» Odpowiedzieli arcykapłani: «Poza Cezarem nie mamy króla». Wtedy więc wydał Go im, aby Go ukrzyżowano.* \n Żadnych szans w starciu z biurokratyczną machiną, więc po co przytaczać jakiekolwiek argumenty. Lepiej zamilknąć. Bezpośredniość Jezusa i błyskotliwość Jego odpowiedzi nawet przekonują Piłata co do faktu niewinności. On nic złego nie uczynił. W dodatku ma wszelkie możliwości, by skorzystać z przywilejów przysługujących Synowi Bożemu i zbawić człowieka w inny sposób – wybiera jednak śmierć krzyżową. Piłat wydaje Jezusa na ukrzyżowanie, nie dlatego, że nie wierzy w jego niewinność, ale dlatego, bo tego wymaga poprawność polityczna i sytuacja, by w dalszym ciągu piastować tytuł Namiestnika. Władza zniewala…",
      "Jezu, naucz mnie by powierzona mi władza zawsze była dla mnie służbą.",
      "### **Stacja 6 Jezus biczowany i koronowany cierniem**",
      "**Kłaniamy Ci się Panie Jezu Chryste i błogosławimy Tobie, żeś przez krzyż i mękę swoją świat odkupić raczył.**",
      "Z Ewangelii Św. Marka:\n *Ubrali Go w purpurę i uplótłszy wieniec z ciernia włożyli Mu na głowę. I zaczęli Go pozdrawiać: «Witaj, Królu Żydowski!» Przy tym bili Go trzciną po głowie, pluli na Niego i przyklękając oddawali Mu hołd. Prorok Izajasz opisuje tą scenę tak: Nie miał On wdzięku, ani też blasku, aby na Niego popatrzeć, ani wyglądu, by się nam podobał. Wzgardzony i odepchnięty przez ludzi, mąż boleści, oswojony z cierpieniem, jak ktoś, przed kim się twarze zakrywa, wzgardzony tak, iż mieliśmy Go za nic. Straszny to widok – jak oni mogli? Bezduszni oprawcy, dobrze, że te czasy minęły – to częste komentarze współczesnych dotyczące sceny biczowania.* \n A dla niektórych ludzi wydanie wyroku i nałożenie kary to w dalszym ciągu za mało, nie zaspokaja to ich satysfakcji. Pełen sukces jest wtedy, gdy kogoś wyszydzę, odbiorę resztki godności, obedrę ze wszystkiego co ma. Na przykład wtedy, gdy ktoś w pracy, czy w życiu publicznym popełnia jakiś błąd. Trzeba Go ubiczować – skomentować z przekąsem, podać dalej koledze, koleżance, niech wszyscy wiedzą, niech się śmieją, niech ma za swoje…",
      "Jezu, naucz mnie bym umiał ocalać innych zamiast ich biczować.",
      "### **Stacja 7 Jezus bierze krzyż na swe ramiona**",
      "**Kłaniamy Ci się Panie Jezu Chryste i błogosławimy Tobie, żeś przez krzyż i mękę swoją świat odkupić raczył.**",
      "Z Ewangelii Św. Jana:\n *I przymusili niejakiego Szymona z Cyreny, ojca Aleksandra i Rufusa, który wracając z pola właśnie przechodził, żeby niósł krzyż Jego. \n Pierwszą refleksją, która może pojawić się w nas po skonfrontowaniu z opisem Ewangelisty jest ta, że Szymon ewidentnie znalazł się w niewłaściwym miejscu i czasie. Wracał do domu, do swojej rodziny, tymczasem zastąpiono mu drogę i przykazano nieść kawał nieczystego drewna, zatem utracił szanse normalnego przygotowania się do Święta Paschy. Niekontrolowana zmiana planów. Byłbyś z takiej zmiany zadowolony? Niewiele wiemy jak wyglądała wspólna droga Jezusa i Szymona na Kalwarię, nie znamy detali, jednak z opisów Pisma Świętego, wiemy, że wydarzyło się podczas niej coś, dzięki czemu Szymon i jego rodzina stali się pierwszymi Chrześcijanami. Gdzie jest Bóg tam są problemy, gdzie są problemy, tam czeka na Ciebie Bóg. Wiarę buduje się poprzez niesienie krzyża.",
      "Jezu, naucz mnie aby doświadczenie udziału w cudzych problemach zbudowało moją wiarę.",
      "### **Stacja 8 Szymon z Cyreny pomaga nieść krzyż Jezusowi**",
      "**Kłaniamy Ci się Panie Jezu Chryste i błogosławimy Tobie żeś przez krzyż i mękę swoją świat odkupić raczył.**",
      "Z Ewangelii Św. Marka: \n *I przymusili niejakiego Szymona z Cyreny, ojca Aleksandra i Rufusa, który wracając z pola właśnie przechodził, żeby niósł krzyż Jego.*",
      "Pierwszą refleksją, która może pojawić się w nas po skonfrontowaniu z opisem Ewangelisty jest ta, że Szymon ewidentnie znalazł się w niewłaściwym miejscu i czasie. Wracał do domu, do swojej rodziny, tymczasem zastąpiono mu drogę i przykazano nieść kawał nieczystego drewna, zatem utracił szanse normalnego przygotowania się do Święta Paschy. Niekontrolowana zmiana planów. Byłbyś z takiej zmiany zadowolony?\nNiewiele wiemy jak wyglądała wspólna droga Jezusa i Szymona na Kalwarię, nie znamy detali, jednak z opisów Pisma Świętego, wiemy, że wydarzyło się podczas niej coś, dzięki czemu Szymon i jego rodzina stali się pierwszymi Chrześcijanami. \nGdzie jest Bóg tam są problemy, gdzie są problemy, tam czeka na Ciebie Bóg. Wiarę buduje się poprzez niesienie krzyża.",
      "Jezu, naucz mnie aby doświadczenie udziału w cudzych problemach zbudowało moją wiarę.",
      "### **Stacja 9 Jezus spotyka niewiasty jerozolimskie**",
      "**Kłaniamy Ci się Panie Jezu Chryste i błogosławimy Tobie, żeś przez krzyż i mękę swoją świat odkupić raczył.**",
      "Z Ewangelii Św. Łukasza:\n *A szło za Nim mnóstwo ludu, także kobiet, które zawodziły i płakały nad Nim. Lecz Jezus zwrócił się do nich i rzekł: Córki jerozolimskie, nie płaczcie nade mną; płaczcie raczej nad sobą i nad waszymi dziećmi. Oto bowiem przyjdą dni, kiedy mówić będą: „Szczęśliwe niepłodne łona, które nie rodziły, i piersi, które nie karmiły”. Wtedy zaczną wołać do gór: Padnijcie na nas; a do pagórków: Przykryjcie nas! Bo jeśli z zielonym drzewem to czynią, cóż się stanie z suchym?»* Paradoksalnie łzy kobiet nie są atrybutem współczucia. Są atrybutem zaślepienia, odwrócenia uwagi od tego co naprawdę istotne, na co zwraca uwagę sam Jezus. Rytualny płacz i lament, który „przysługiwał” każdemu konającemu i skazańcowi, powielanie utartych, ziemskich schematów – bo tak wypada, bo tak się przyjęło, bez refleksji na temat istoty problemu – nie tak jako chrześcijanie mamy czynić. Łzy są zbyt cenne – zachowaj je więc na okazję, gdy być może będziesz zmuszony zapłakać nad swoim losem, jak Piotr. Właśnie takie przesłanie kieruje do niewiast nasz Mistrz.",
      "Jezu, naucz mnie postawy refleksji nad sobą.",
      "### **Stacja 10 Jezus przybity do krzyża**",
      "**Kłaniamy Ci się Panie Jezu Chryste i błogosławimy Tobie, żeś przez krzyż i mękę swoją świat odkupić raczył.**",
      "Z Ewangelii Św. Łukasza:\n Gdy przyszli na miejsce, zwane «Czaszką», ukrzyżowali tam Jego i złoczyńców, jednego po prawej, drugiego po lewej Jego stronie. Lecz Jezus mówił: «Ojcze, przebacz im, bo nie wiedzą, co czynią». \n Dopóki gwoździe nie przybiły ciała do krzyża, Jezus posiadał jeszcze niewielką przestrzeń wolności. Mógł kontrolować ruchy swojego ciała. Od aktu ukrzyżowania znajduje się już całkowicie uwięziony w drzewie, w niewoli krzyża. Jest zdany na innych ludzi. To oni zdecydują, co z nim zrobią. Żadnej kontroli. Wydawać by się mogło, że nie może już nic. A jednak – może decydować o swojej postawie wobec innych: z drzewa krzyża przebacza! Viktor Frankl, psychiatra, były więzień Auschwitz i Dachau napisze po latach: Człowiekowi można zabrać wszystko za wyjątkiem jednej rzeczy: ostatniej z ludzkich wolności - wyboru swojej postawy w każdych okolicznościach, wyboru swojej drogi. To lekcja wzięta wprost z krzyża.",
      "Jezu, naucz mnie dobrego korzystania z wolności, którą mi dałeś.",
      "### **Stacja 11 Jezus obiecuje swoje Królestwo żałującemu łotrowi**",
      "**Kłaniamy Ci się Panie Jezu Chryste i błogosławimy Tobie, żeś przez krzyż i mękę swoją świat odkupić raczył.**",
      "Z Ewangelii Św. Łukasza:\n Lecz drugi,[ze złoczyńców] karcąc go, rzekł: «Ty nawet Boga się nie boisz, chociaż tę samą karę ponosisz? «My przecież - sprawiedliwie, odbieramy bowiem słuszną karę za nasze uczynki, ale On nic złego nie uczynił». I dodał: «Jezu, wspomnij na mnie, gdy przyjdziesz do swego królestwa». Jezus mu odpowiedział: «Zaprawdę, powiadam ci: Dziś ze Mną będziesz w raju».\n Wisieli ramię w ramię. Krzyż obok krzyża Jednocześnie moralnie, obaj byli bardzo daleko Boga: złodzieje, rozbójnicy, oszuści, być może zabójcy. Nie można powiedzieć, że jeden był bliżej a drugi dalej, jeden zgrzeszył mniej a drugi bardziej. Co ich poróżniło? Był to stosunek do prawdy o sobie i o Bogu, którą tylko jeden z łotrów był gotów uznać:. A Kto spełnia wymagania prawdy, zbliża się do światła, aby się okazało, że jego uczynki są dokonane w Bogu. Dla Jezusa Twój grzech, Twoje oddalenie nie stanowią żadnego problemu, jeżeli tylko jesteś gotów zwrócić się ku Bogu – nie musisz się do tego specjalnie przygotowywać. \n Jezu, naucz mnie zbliżać się do Twojego światła, nie zważając na to jak blisko lub daleko Ciebie dziś jestem.",
      "### **Stacja 12 Matka i umiłowany uczeń pod krzyżem Jezusa**",
      "**Kłaniamy Ci się Panie Jezu Chryste i błogosławimy Tobie, żeś przez krzyż i mękę swoją świat odkupić raczył.**",
      "Z Ewangelii Św. Jana:\n *Jezus więc, gdy zobaczył Matkę i stojącego przy niej ucznia, którego miłował, zwrócił się do Matki: Kobieto, oto twój syn! Następnie powiedział do ucznia: Oto twoja matka! I od tej godziny uczeń wziął ją do siebie.* \n Umierający Jezus troszczy się o relacje, które budował za życia. W chwili, gdy siły Go już opuszczają a ból jest tak silny, że powoduje omdlenia resztką tchu wypowiada swój ostatni testament. Powierza dwoje bliskich mu ludzi sobie nawzajem. Co mogła czuć wtedy kobieta stojąca pod krzyżem? Spodziewamy się, że ją bardzo bolało, każdą matkę której zabijają dziecko boli. Co mógł czuć uczeń, gdy okazało się, że jego Mistrz ponosi sromotną klęskę? Pewnie mógł zaprzątać sobie głowę myślami po co mu było to wszystko i co z nim dalej będzie? Postawa dwójki stojącej pod krzyżem jest jednak inna: nie koncentrują się na sobie, na tym co indywidualnie czują, jak bardzo jest im źle ze śmiercią Jezusa, tylko są ze sobą i wzajemnie się wspierają. Dzięki dojrzałości relacji, które zbudowali z Jezusem testament z krzyża może być zrealizowany.",
      "Jezu, naucz mnie budować dojrzałe relacje z bliskimi.",
      "#### **Stacja 13 Jezus umiera na krzyżu**",
      "**Kłaniamy Ci się Panie Jezu Chryste i błogosławimy Tobie, żeś przez krzyż i mękę swoją świat odkupić raczył.**",
      "Z Ewangelii Św. Łukasza:\n *Było już około godziny szóstej i mrok ogarnął całą ziemię aż do godziny dziewiątej. Słońce się zaćmiło i zasłona przybytku rozdarła się przez środek. Wtedy Jezus zawołał donośnym głosem: Ojcze, w Twoje ręce powierzam ducha mojego. Po tych słowach wyzionął ducha.* \n Cytując za Kard. Wyszyńskim: Każda miłość musi być próbowana i doświadczana. Ale gdy wytrwa, doczeka się nagrody - zwycięskiej radości. Każda miłość prawdziwa musi mieć swój Wielki Piątek. Kochać i umrzeć, kochać i pokonać śmierć… tak kochać może tylko Bóg.",
      "Jezu, naucz mnie kochać.",
      "### **Stacja 14 Jezus zdjęty z krzyża i złożony do grobu**",
      "**Kłaniamy Ci się Panie Jezu Chryste i błogosławimy Tobie, żeś przez krzyż i mękę swoją świat odkupić raczył.**",
      "Z Ewangelii Św. Jana:\n *Zabrali więc Jezusa i obwiązali je w płótna razem z wonnościami, stosownie do żydowskiego sposobu grzebania. A na miejscu gdzie Go ukrzyżowano, był ogród, w ogrodzie zaś nowy grób, w którym jeszcze nie złożono nikogo. Tam to więc ze względu na żydowski dzień przygotowania złożono Jezusa, bo grób znajdował się w pobliżu.* \n Zdrada, opuszczenie przez uczniów, sfingowany proces, wyszydzenie, męcząca droga na Kalwarię i w końcu haniebna śmierć… Mimo tylu zniechęcających wydarzeń, wciąż są osoby dla, których Jezus jest bliski. Wciąż są przy nim. Kochają go, więc organizują mu pochówek. Moc wiary, moc Boga, moc prawdziwej Relacji, która nie kończy się z chwilą śmierci, ale dalej trwa. Bo śmierć to dopiero początek Życia, a grób po pewnym czasie staje się pustym grobem… Wierzysz w to?",
      "Jezu, naucz mnie bym w śmierci widział początek.",
      "### **Zakończenie**",
      "Z Pierwszego Listu do Koryntian: \n *Lecz powie ktoś: A jak zmartwychwstają umarli? W jakim ukazują się ciele? O, niemądry! Przecież to, co siejesz, nie ożyje, jeżeli wprzód nie obumrze (…) Zasiewa się zniszczalne — powstaje zaś niezniszczalne, sieje się niechwalebne — powstaje chwalebne; sieje się słabe — powstaje mocne (…) A kiedy już to, co zniszczalne, przyodzieje się w niezniszczalność, a to, co śmiertelne, przyodzieje się w nieśmiertelność, wtedy sprawdzą się słowa, które zostały napisane: Zwycięstwo pochłonęło śmierć. Gdzież jest, o śmierci twoje zwycięstwo? Gdzież jest, o śmierci, twój oścień? Ościeniem zaś śmierci jest grzech, a siłą grzechu Prawo. Bogu niech będą dzięki za to, że dał nam odnieść zwycięstwo przez Pana naszego Jezusa Chrystusa.*"
    ],
    summary: "Rozważania przygotowane przeze mnie dla Duszpasterstwa Młodzieży przy Bazylice Ojców Karmelitów Na Piasku. Wraz z prezentacją zostały wykorzystane do Nabożeństwa Biblijnej Drogi Krzyżowej 12.04.2019r. ",
    alt: "Biblijna Droga Krzyżowa",
    flagWatermark: "26/07/2023 M.R.",
    image: chrustus,
    imageMin: chrustusMin,
    width: "614",
    height: "1024",
    widthMin: "632",
    heightMin: "474",
    flagColor: "flag-title-dark",
    tags: []
  },
  {
    id: 2,
    title: "ŻonkilowePodajDalej",
    text: [
      "Chociaż od social mediów i różnych “dziwnych” form pomocy dla potrzebujących(?) stronię, w tej akcji wzięłam udział. Dlaczego? Dlatego, że cel akcji w mojej ocenie jest bardzo właściwy a forma również nie sprawiła mi problemów. Zatem w mojej kategorii jest to mądra pomoc, którą warto wspierać.",
      "O co chodzi?",
      "*Z okazji 24 edycji Pól Nadziei, podczas której prowadzenie tradycyjnych kwest było bardzo ograniczone, Towarzystwo Przyjaciół Chorych „Hospicjum im. św. Łazarza\" w Krakowie zaprosiło uczestników do udziału w wiosennej akcji w mediach społecznościowych pod nazwą #ŻonkilowePodajDalej, której celem było wyrażenie troski o chorych i pozyskanie funduszy na działalność Hospicjum św. Łazarza.*\n*Poprzez narysowanie/sfotografowanie żonkilowego kwiatu i podzielenie się tym obrazem w mediach społecznościowych sprawiono, że chorzy doświadczyli namiastki wiosny.*",
      "Można by rzec zbiórka jakich wiele. No właśnie nie. Zgodzę się z faktem, że w ostatnim czasie namnożyło się  wiele inicjatyw charytatywnych  co do których charytatywności, mądrości i wartości dodanej mogłabym mieć spore zastrzeżenia, ale nie tutaj. Dlaczego?",
      "Tak więc ad.1 - cel: pacjenci hospicjum to osoby terminalnie chore, to nie ludzie, którym się nie chce lub nie umieją lub szukają innych wymówek. Hospicjum od lat utrzymuje się z datków i zbiórek a tych z uwagi na lockdowny przeprowadzić w tradycyjnej formie się nie dało.",
      "Ad. 2 - forma: kwiaty typu żonkil czy też w zimowej wersji śpiewanie kolęd to czynności/ rzeczy bliskie gronu pacjentów hospicjum. Oglądanie pięknie wykonanych prac jest wartością dodaną a przelane pieniądze pozwolą na zaspokojenie tych najpilniejszych potrzeb zdrowotnych podopiecznych Hospicjum.. Forma też jest dla każdego, bo o ile nie każdy potrafi rysować o tyle zdjęcie wykona już każdy.",
      "Tak więc wyrazy uznania dla Towarzystwa Przyjaciół Chorych „Hospicjum im. św. Łazarza\" w Krakowie. Ogromne podziękowania za waszą pracę.",
      "A gdyby ktoś myślał, że akcja dawno temu się skończyła i temat nieaktualny to **śpieszę wyjaśniać, że potrzeby Hospicjum cały czas są ogromne i Twój przelew na pewno szybko zostanie mądrze spożytkowany.**"
    ],
    summary: "Chociaż od social mediów i różnych “dziwnych” form pomocy dla potrzebujących(?) stronię, w tej akcji wzięłam udział. Dlaczego? Dlatego, że cel akcji w mojej ocenie jest bardzo właściwy a forma również nie sprawiła mi problemów. Zatem w mojej kategorii jest to mądra pomoc, którą warto wspierać...",
    alt: "Zbiórka na rzecz hospicjum",
    flagWatermark: "26/07/2023 M.R.",
    image: zonkile,
    imageMin: zonkileMin,
    width: "1288",
    height: "1717",
    widthMin: "632",
    heightMin: "474",
    linkTitle: "Wirtualna puszka hospicjum",
    linkAlt: "Darowizna",
    linkHref: "https://hospicjum.krakow.pl/wirtualna-puszka/",
    linkText: "Wirtualna puszka hospicjum:",
    linkClass: "btn-donation",
    tags: [
      "Mądra pomoc",
      "ŻonkilowePodajDalej",
      "Hospicjum Św. Łazarza"
    ],
    flagColor: "flag-title-bright"
  },
  {
    id: 3,
    title: "Wielopiętrowe życie w niskim świecie",
    text: [
      "Osobą i życiem Christiana de Charge zainteresowałam się po raz pierwszy po medytacji nad jego testamentem. Już wtedy dostrzegłam jak genialny był to człowiek. Czułam to, ale nie widziałam dlaczego jest mi tak bliski? Co w nim jest? Po lekturze testamentu zapragnęłam poznać go bardziej. Internet, chociaż to podobno skarbnica wiedzy, pozwolił jedynie na zgłębienie prostych faktów z jego życiorysu: data urodzenia, krótki rys jak został trapistą, co działo się z nim w Algierii jak zginął. Trochę więcej można było przeczytać na temat faktów związanych z jego śmiercią i późniejszą beatyfikacją - kościół katolicki wyniósł Christiana, razem z pozostałymi zamordowanymi współbraćmi algierskiego klasztoru do godności błogosławionych. Jednak to w dalszym ciągu nie były informacje, które pozwoliłyby mi na spotkanie Christiana jako człowieka. Klimat jego życia nieco bardziej pomógł mi odnaleźć film Ludzie Boga  reżyserii Xaviera Beauvios. Film przybliża kulminacyjne punkty życia mnichów w klasztorze Tibhirine w Algierii oraz daje poruszające świadectwo dialogu, męczeństwa i śmierci zakonników (na marginesie film spotkał się ze świetnymi recenzjami krytyków, nagrodzony Grand Prix Cannes oraz francuskim Cesarem). Natomiast po jego lekturze w dalszym ciągu odczuwałam głód w poznaniu tej świetlistej postaci jaką wydawał mi się być  przełożony wspólnoty w Tibhirine - Christian.",
      "Dlatego następnym krokiem była lektura książki „Ludzie Boga”.  Książka jest zbiorem  pism  Christiana de Charge z lat 1974-1996. Już po przeczytaniu kilku pierwszych stron stwierdziłam, że trzymam w ręku ogromny skarb. W tej lekturze niewątpliwie spotkałam Christiana: tego prawdziwego, który owszem został zamordowany, ponieważ pozostał wierny swojemu powołaniu (albo jak twierdzą niektórzy naiwnie igrał z Islamem), ale przede wszystkim spotkałam człowieka, który każdego dnia wyrażał swój podziw nad każdym stworzonym człowiekiem: tym inaczej myślącym, tym o różnym kolorze skóry, innych zdolnościach, majątku, tym mówiącym obcym językiem oraz wierzącym inaczej. Christian odnajdywał sens w każdym dniu i w każdej sytuacji jaką dano mu było przeżyć. Kontemplował życie, które nie ma sufitu, które w żaden sposób nie jest limitowane. Jednocześnie dopingował siebie i innych, aby wciąż wzrastać. Jak pisał o tym w książce tego nauczyła go modlitwa:",
      "*\"(...) życie nie jest sytuacją osiągniętą raz na zawsze, ale jest pragnieniem, które ma wzrastać stopniowo, niczym wielopiętrowy dom. Nie żyjemy długo na jednym poziomie na tym niskim świecie.\"*",
      "Cytowane słowa to jedne z wielu z książki zasługujące na dłuższą medytację oraz (jeżeli jesteś wierzący) na rachunek sumienia.",
      "Czy faktycznie moje życie wygląda tak, że dobudowuje kolejne piętra wznosząc się w górę? Czy może odwrotnie: to co buduje to potężne okopy głęboko osadzone w betonowych fundamentach, od których nie chcę się oderwać? Czy pamiętam, że moim przeznaczeniem są wysokie loty? A gdzie w tym wszystkim jest drugi człowiek? Jest rywalem, któremu muszę dokopać czy partnerem, z którym idę ramię w ramię?",
      "Człowiek pewnego dnia, będzie musiał odejść z niskiego świata a o wartościowości życia, które przeżył chyba nie będzie świadczyć ilość przeżytych lat i rodzaj śmierci jaką zginął. Być może zamiast nieustannie zamartwiać się o zaspokajanie wszystkich potrzeb wielkiego świata i wartości, które muszę za wszelką cenę obronić, lepiej kontemplować małość tegoż i chwalić wolność nam daną i zadaną, która wznosi nas ku górze?"
    ],
    summary: "Osobą i życiem Christiana de Charge zainteresowałam się po raz pierwszy po medytacji nad jego testamentem. Już wtedy dostrzegłam, jak genialny był to człowiek. Czułam to, ale nie widziałam dlaczego jest mi tak bliski? Co w nim jest?...",
    alt: "Photo by Wiretock /Freepik",
    flagWatermark: "26/07/2023 M.R.",
    image: gory,
    imageMin: goryMin,
    width: "1288",
    height: "966",
    widthMin: "632",
    heightMin: "474",
    linkTitle: "Więcej o postaci",
    linkAlt: "Więcej o postaci",
    linkHref: "https://en.wikipedia.org/wiki/Christian_de_Cherg%C3%A9",
    linkText: "Więcej o postaci",
    linkClass: "btn-more-character",
    tags: [
      "Christian de Charge",
      "trapiści,",
      "mnich",
      "świętość,",
      "życie",
      "marzenia",
      "Ludzie Boga",
      "książka",
      "heroizm",
      "męczeństwo",
      "genialne życie",
      "wolność"
    ],
    flagColor: "flag-title-bright"
  },
  {
    id: 4,
    title: "01.08 Czterdzieści Cztery",
    text: [
      "Wspólna lektura prasy z uroczą, energiczną, 95-latką. Czytamy właśnie artykuł o podróżowaniu. Jest coś koło 17. Lekturę przerywają nam syreny…",
      " -Powstanie (cisza), Wybuchło powstanie.",
      "(dłuższa cisza)",
      "-Od razu było wiadomo, że coś się dzieje. Niemcy wpadli do domu. Coś odburknęli. Wypadli. Poddenerwowani. Nie wrócili. -",
      "W głosie Pani daje się wyczuć autentyczne emocje. Mieszanina strachu, niepewności, ale też delikatne podekscytowanie… Intensywnie myślę, co odpowiedzieć… nie znajduję słów. Słucham dalej.",
      "-My tu (czyt. w wiosce pod Krakowem) za dużo wtedy nie wiedzieliśmy… -",
      "Wydaje się, że mówione neutralnym tonem, jednak bolesne wspomnienia przeszkadzają mówić płynnie…(długa cisza) Pani ożywia i wzmacnia głos, oczy zaczynają jej błyszczeć.",
      "-Aż wreszcie w następne dni (czyt. pierwsze dni powstania – drobne sukcesy powstańców) ludzie mówią nam: Warszawa wolna, Warszawa wolna –",
      "W głosie rozmówczyni nie wyczuwam patosu, dumy, boleści, pretensji, chęci manifestacji czegokolwiek. Daje się jednak usłyszeć autentyczny, świeży powiew nadziei, instynktu życia silniejszego niż śmierć. Przełykam ślinę. Milczymy wpatrując się w siebie…",
      "*„Warszawa wolna”* … Dziś, po znanych rezultatach powstania, po znojach i trudach czasu powojennego, po x latach życia w wolności w głosie staruszki wciąż słyszę tą zmartwychwstającą wczesnosierpniową nadzieję wolności.",
      "Powstanie – życiodajna Iskierka wiary w wolność, która dla innych przyjęła formę wyroku śmierci.",
      "Nie próbujmy odpowiadać na pytania, na które i tak nie znajdziemy odpowiedzi. Zamiast w kółko uparcie manifestować skrajności – uczmy się historii, szukając w niej życia."
    ],
    footerText: "Tekst ukazał się pierwotnie na moim prywatnym profilu na fb 01.08.2017",
    summary: "Wspólna lektura prasy z uroczą, energiczną, 95-latką. Czytamy właśnie artykuł o podróżowaniu. Jest coś koło 17. Lekturę przerywają nam syreny… - Powstanie (cisza), Wybuchło powstanie.\n (dłuższa cisza)\n - Od razu było wiadomo, że coś się dzieje. Niemcy wpadli do domu. Coś odburknęli. Wypadli. Poddenerwowani. Nie wrócili...",
    alt: "Rocznica wybuchu Powstania Warszawskiego",
    flagWatermark: "26/07/2023 M.R.",
    image: largeOfficeBuilding,
    imageMin: largeOfficeBuildingMin,
    width: "1288",
    height: "850",
    widthMin: "632",
    heightMin: "474",
    link: "https://www.freepik.com",
    link1: "https://pl.freepik.com/darmowe-zdjecie/duzy-budynek-biurowy_945371.htm#query=warszawa&position=19&from_view=search&track=sp",
    linkTitle: "Photo by Freepik.com",
    linkTitle1: "Obraz autorstwa bedneyimages",
    tags: [
      "Warsaw uprising",
      "Powstanie 44",
      "Rocznica",
      "Pamięć",
      "Życie",
      "Nadzieja",
      "Nie oceniaj",
      "Szanuj"
    ],
    flagColor: "flag-title-bright"
  },
  {
    id: 5,
    title: "Dostrzec w sobie wartość",
    text: [
      "**Podobno pisanie pomaga w radzeniu sobie z emocjami. Więc…?:)**",
      "Znam kogoś, kto jako dziecko miał długą absencję w zajęciach lekcyjnych spowodowaną chorobą. Mówili o nim, że pewnie będzie musiał powtarzać rok – ten ktoś ukończył semestr z wynikiem w top 3 swojej klasy.\nZnam kogoś, kto w młodzieńczych latach był wątły, słaby i z kiepskimi wynikami w biegach. Mówiono, że w zawodach sportowych nic nie osiągnie – ta osoba w późniejszych latach zdobyła medal w zawodach rangi wojewódzkiej i była kapitanem drużyny na turnieju.\nZnam kogoś, kto w młodzieńczych latach był wątły, słaby i z kiepskimi wynikami w biegach. Mówiono, że w zawodach sportowych nic nie osiągnie – ta osoba w późniejszych latach zdobyła medal w zawodach rangi wojewódzkiej i była kapitanem drużyny na turnieju.\nZnam kogoś, kto w szkole „wymiatał z matematyki”, ale podobno to wykluczało dobrą umiejętność redagowania tekstów – po latach artykuł tego kogoś kupił i opublikował czołowy portal pewnej branży w kraju i na świecie a redaktor naczelny podsumował tekst stwierdzeniem „Bardzo dobry!”\nZnam kogoś, kto ze względu na swoją kiepską sytuację rodzinną, w ocenie postronnych, miał mieć poważne braki relacyjne w dorosłym życiu – ta osoba ma przyjaciół do grobowej deski, mnóstwo znajomych i drugą połówkę.\n      Znam kogoś, kto ze względu na swoje pochodzenie i brak znajomości, w ocenie innych, miał nie zrobić kariery. Teraz to były PM-em w topowych projektach swojej branży, współpracuje z największymi, jest cenionym pracownikiem. Lider kilku ciekawych, globalnych wręcz, projektów społecznych.\nZnam kogoś kto jako dziecko nie był zapraszany do akademii, różnych przedstawień i wystąpień publicznych, bo „się nie nadawał” – ta osoba w swoim dorosłym życiu udzieliła kilku wywiadów w TV, była zapraszana na kolejne, w tym programy „na żywo”.\nZnam kogoś, kto zdaniem jego nauczyciela „nie umiał angielskiego” – ta osoba za jakiś czas tłumaczyła swojego kolegę „z polskiego na angielski” na międzynarodowej konferencji.\nZnam kogoś o kim „profesor” z liceum twierdził, że czyta słabo – parę lat później profesor tytularny zachwycił się tą osobą jako swoim prywatnym lektorem …\nZnam kogoś… Ty też pewnie znasz. W tym miejscu idealnym będzie przytoczyć historię, która kilka dni wcześniej przykuła moją uwagę. Powyższy przykład tylko potwierdza jej autentyczność. Trzymajcie z ludźmi, którzy umieją dostrzec w Was wartość!A oto i historia(autor nieznany):",
      "*„Ojciec powiedział do córki: Z wyróżnieniem skończyłaś szkołę. Oto samochód, który kupiłem wiele lat temu. Teraz jest trochę starszy, ale zanim ci go dam, zabierz na giełdę używanych samochodów w centrum i powiedz im, że chcesz go sprzedać i zobacz ile ci za to oferują.\"Córka poszła na giełdę używanych pojazdów, wróciła do ojca i powiedziała:\" Zaoferowali mi 1.000 euro, bo mówili, że wygląda na zużyty.\"Ojciec zaproponował: ′′Idź do lombardu\". Okazało się, że lombard zaoferował tylko 100 euro, bo to stary samochód.Ojciec poprosił córkę, aby teraz poszła do klubu samochodowego i pokazała im samochód. Wobec tego córka pojechała samochodem do klubu, wróciła i powiedziała ojcu: ′′Niektórzy w klubie zaoferowali 100.000 euro, bo to Holden Torana i kultowy samochód i poszukiwany przez wielu kolekcjonerów.\"Teraz ojciec powiedział swojej córce: \"Właściwe miejsce ceni cię w odpowiedni sposób\"*.",
      "Jeśli nie jesteś ceniony, nie złość się, to znaczy, że jesteś w złym miejscu. Nigdy nie zostawaj w miejscu, gdzie nikt nie widzi Twojej wartości.”"
    ],
    footerText: "Tekst ukazał się pierwotnie na moim prywatnym profilu na fb 04/2021",
    summary: "Podobno pisanie pomaga w radzeniu sobie z emocjami. Więc…?:) Znam kogoś, kto jako dziecko miał długą absencję w zajęciach lekcyjnych spowodowaną chorobą. Mówili o nim, że pewnie będzie musiał powtarzać rok – ten ktoś ukończył semestr z wynikiem w top 3 swojej klasy...",
    alt: "Tekst o istocie własnej wartości",
    flagWatermark: "26/07/2023 M.R.",
    image: sedanParkedAtAdesertedAreaUnderAcloudySky,
    imageMin: sedanParkedAtAdesertedAreaUnderAcloudySkyMin,
    width: "1288",
    height: "966",
    widthMin: "632",
    heightMin: "474",
    link: "",
    link1: "",
    linkTitle: "Photo by Freepik.com",
    linkTitle1: "Obraz autorstwa bedneyimages",
    tags: [
      "Emocje",
      "poczucie własnej wartości",
      "rozwój",
      "unikalność",
      "wyjątkowość "
    ],
    flagColor: "flag-title-bright"
  },
  {
    id: 6,
    title: "Jak znaleźć przygodę?",
    text: [
      "Być może zdarzyło Ci się przeglądać czyjeś zdjęcia w internecie z poczuciem zazdrości “inni to mają dobrze”. Cuda natury, zabytki, egzotyczne kraje, imprezy, podczas gdy ty siedzisz w domu i jedyne co widzisz to innych ludzi w drodze do pracy. Widzisz jeszcze wkurzającego szefa, korki albo tłok w komunikacji miejskiej przy powrocie. Wracasz, jesz śpisz, wstajesz. Mija dzień za dniem. Wciąż to samo. Aż wreszcie wakacje. Zbierasz swoją rodzinę i jedziesz, powiedzmy do Zakopanego, po czym frustrujesz się w kolejce na Giewont. Albo wykupujesz zagraniczną wycieczkę i spędzasz tydzień  w hotelowym mirze z prywatną plażą. Wracasz do domu. Niby było miło, ale Twoje wakacje wydają Ci się takie zwyczajne, znowu trzeba czekać rok na kolejne, znowu brak przygód. A czy zadałaś/eś sobie pytanie czy i dlaczego tak to działa?\n",
      "Może dlatego, że przygody i ekscytująca wydarzenia nigdy nie pojawiają się na Twoje zawołanie, bo akurat Ty masz wakacje. Spróbuj więc znaleźć przygodę najpierw w drodze do pracy. Ciekawe życie, aby było  faktycznie ciekawe musisz odnaleźć najpierw w sobie :)",
      "P.S.To zdjęcie w poście zrobiłam wałęsając się po jakiejś mieścinie we Włoszech, ponieważ nie rozumiem super włoskiego treść napisu na ścianie nie była mi znana. Na szczęście po kilku miesiącach od pstryknięcia fotki zdecydowałam się na uruchomienie translatora:) Napis brzmi: Życie jest jak lustro: uśmiecha się do ciebie, jeśli patrzysz na nie uśmiechnięty",
      "**P.S.2 W ramach pracy nad budowaniem w sobie uważnosci na uchwycenie przygód zachęcam Cię do wykonania szybkiego i prostego postanowienia**: w swojej najbliższej drodze z pracy do domu bądź obserwatorem. Po skończonej podróży wymień  jedną lub dwie rzeczy, które w jakiś sposób Cię zaskoczyły? Podrąż nieco  temat: czego one dotyczyły, jak sądzisz dlaczego akurat one jakoś były dla Ciebie w pewien sposób ważne?"
    ],
    footerText: "",
    summary: "Być może zdarzyło Ci się przeglądać czyjeś zdjęcia w internecie z poczuciem zazdrości “inni to mają dobrze”. Cuda natury, zabytki, egzotyczne kraje, imprezy, podczas gdy ty siedzisz...",
    alt: "Jak znaleźć przygodę?",
    flagWatermark: "26/07/2023 M.R.",
    image: jimMorrison,
    imageMin: jimMorrisonMin,
    width: "1288",
    height: "723",
    widthMin: "632",
    heightMin: "474",
    link: "",
    link1: "",
    linkTitle: "",
    linkTitle1: "",
    tags: [],
    flagColor: "flag-title-bright"
  },
  {
    id: 7,
    title: "Kochać oznacza wystawiać się na ryzyko",
    text: [
      "**Czym jest miłość? Wszyscy o niej mówią, wszyscy o niej marzą, ale do tej pory nie doczekała się jednej i niezmiennej definicji… Dlaczego?**",
      "Czasami nawet wbrew sobie, nadarza mi się  możliwość obserwacji  par w różnych miejscach publicznych. Patrzeć na ich zachowanie, gesty, sposób w jaki się do siebie odnoszą. Jak, przy okazji czasu razem, widzą inne osoby, czy je w ogóle zauważają, są skupieni na sobie, jakie mają motywacje? Chociaż generalizowanie niekoniecznie jest w porządku, to z moich obserwacji z czasem wyłonił się podział: z tymi ludźmi fajnie pogadać, poznać, może nawiązać relację a od tamtych par chcę stronić z daleka. Może nie robią nic złego, jednak w ich zachowaniu wyczuwam coś, co spotykając się z tym dwojgiem ludzi sprawia, że dużo mnie to spotkanie kosztuje. Na początku nie wiedziałam o co chodzi? Może to kwestia wychowania, pochodzenia, kultury osobistej dwojga osób, sposobu dobierania się? Odpowiedź, była przecząca. Nawet  u osób, za którymi prywatnie nie przepadam zdarza się, że gdy ta osoba jest w związku - całkiem przyjemnie mi się z tą parą  rozmawia, bywa też odwrotnie - z osobna z każdą z pary jest super, ale gdy są razem - spotkanie oni+ja jakoś nie służy. Jako, że odpowiedź na powyższe pytanie  o kryteria podziału par w  żaden sposób nie stała się moim życiowym celem - pozostało więc przed długie lata bez odpowiedzi.",
      "Jednocześnie stając się dojrzałym człowiekiem coraz częściej pytałam siebie o miłość, związek, rodzinę. Nie chcąc polegać na ludowej mądrości szukałam w książkach, podręcznikach, artykułach.  Przykuwały mnie też przykłady, najmocniej te pozytywne. Z takiej ilości zgromadzonych informacji można było się efektywnie uczyć i chyba się to udało. Skoro ilu ludzi tyle definicji miłości poszukałam swojej własnej. W pakiecie przyszła odpowiedź na pytanie o kryterium podziału par: jedne się kochają, inne w mniejszym lub większym stopniu bardziej pożądają.\n",
      "Walentynki, czerwone serduszka, motyle w brzuchu. Ciągłe podekscytowanie, różowe okulary… brakuje  tylko słowa miłość. Popkultura twierdzi, że ten rzeczownik wkomponowuje się w  poniższą listę idealnie, natomiast dawka wiedzy, którą otrzymałam odpowiada: nie tak prędko, od zakochania do miłości nie przechodzi się z automatu. Tym sposobem wyodrębniłam podział na “zwierzęcą” i “ludzką” składową  budowania związków. Był to krok milowy do zrozumienia podstawowych mechanizmów człowieka oraz nauki kochania.",
      "“Część zwierzęca”: zaczyna się od zakochania i o wszystkim decyduje chemia naszego mózgu, neuroprzekaźniki, hormony. Człowiek to zwierzę, które chce się rozmnażać i przetrwać. Tak zaprojektowała nas ewolucja. Czujemy pociąg seksualny do osoby, która jest odpowiednim materiałem genetycznym. Dosadne wyrażenie, ale to właśnie tak (w dużym uproszczeniu) działa nasz mózg - przynajmniej jego zwierzęca część. Stąd też zakochujemy się w kimś i zapominamy o bożym świecie. Gdy natrafimy na pozytywną odpowiedź zwrotną od innego osobnika - łączymy się w parę.  Naszego wybranka idealizujemy, chcemy spędzać z nim cały wolny czas, kochać się itd. itd. Nic nam nie przeszkadza, o nic nie pytamy. Później, w zależności od płci, relacja i reakcje wyglądają  nieco odmiennie, niemniej można by rzec… po zwierzęcemu: kłótnie i zgody, dominacja i przywiązanie, wcielanie w rolę, dopasowywanie do potrzeb świata, walka o swoją pozycję w związku i wspólna walka o pozycje związku w grupie, pożądanie. Generalnie samo życie. Może się pojawiać pytanie: po co się tak męczyć, skoro to takie głupie? Szybka odpowiedź - bo to się nam  jako gatunkowi opłaca, dlatego mózg  nas ku temu pcha (na marginesie - mężczyzna w czasach prehistorycznych odszedł  od związków poligamicznych, bynajmniej nie  z pobudek moralnych, tylko właśnie z faktu dbania o interes gatunku - gdy nie istniała antykoncepcja w plemionach kwitły choroby weneryczne, które w przypadku częstych kontaktów seksualnych pomiędzy różnymi członkami potrafiły szybko  uśmiercić całe plemię). Czy można jednak inaczej? Odpowiedź poniżej.",
      "“Część ludzka” - gdy mózg zwierzęcy  zadziała - do głosu może, choć nie musi dojść “mózg ludzki”, który uruchamiać się może również w każdej  innej, nie mającej seksualnego wymiaru relacji, który mówi: zależy mi na Twojej osobie.  Miłość jest więc decyzją człowieka: chcę Twojego dobra, chcę go na zawsze. Dlatego z Tobą przebywam, pomagam Ci w Twoich trudnościach,  opiekuję się Tobą. Dla Ciebie stawiam sobie coraz wyższe wymagania, rezygnuję z rzeczy nieistotnych, rozwijam się. W relacji dbam o odpowiednią komunikację i potrzeby drugiej strony. Nie dominuję - jestem partnerem. Co ważne moja decyzja może spotkać się z różną reakcją  - może zostać zaakceptowana, przyjęta, odwzajemniona, odrzucona. Druga strona może kochać, może chcieć, ale nie umieć. Może nas zranić lub odrzucić, starać mniej lub bardziej, może się wycofać. Decydując o miłości wobec osoby zgadzam się na podjęcie ryzyka i przyjęcie konsekwencji swojego i cudzego działania, zgadzam się na naukę i wysiłek, który będę wkładał w budowanie relacji już do końca, zgadzam się na możliwość popełnienia błędu. Daję prawo do szacunku, odmiennego zdania, przeprosin, mówienia nie.  Kto nie umie zaakceptować ryzyka jakie wpisane jest w tą ludzką relacyjność ten nie będzie potrafił kochać. Może jedynie pożądać. Jeżeli jednak moja decyzja: zależy mi  na Twoim dobru, spotka się z Twoją decyzją: mnie również zależy na Tobie, wtedy wpadamy sobie w najczulsze ramiona miłości. Tworzymy związek, który może wszystko przetrwać i pomóc pokonać każdy problem. Dojrzewanie do takich wyborów trwa długo, wymaga ciężkiej pracy nad sobą i potężnego wysiłku. Natomiast owoce tej pracy rekompensują wszelkie trudy.",
      "Decydując się na założenie związku mamy przywilej dokonywania autonomicznych wyborów: zwierzak czy człowiek ? Mamy również prawo do nie akceptowania wyborów innych. Według moich obserwacji obranie ścieżki “najpierw człowiek, później zwierzak”, najpierw decyzja, później domino wydarzeń stwarza przestrzeń do zakochania w kontrolowanych  warunkach i nie dając ślepo podążać popędom. Jest to gwarancja stworzenia takiego związku, w którego towarzystwie każdy będzie chciał przebywać. Taka droga wymaga wysiłku i solidnego przepracowania siebie, które dla wielu ludzi postępu nie są akceptowane. Pozostaje nam uszanować ich wybór oraz na tyle, na ile się pozwolą, kochać ich tak jak umiemy.",
      "*Kochać oznacza wystawiać się na ryzyko. Nieważne, co pokochasz - twoje serce z pewnością będzie cierpieć, może nawet zostanie złamane. Jeśli chcesz je uchronić w nienaruszonym stanie, nie wolno ci go oddawać nikomu i niczemu, nawet zwierzęciu. Starannie zamknij je w ramach hobby i drobnych luksusów, unikaj wszelkich uwikłań, bezpiecznie zamknij je na klucz w szkatułce czy też trumnie własnego samolubstwa. Jednak pozostając w takiej szkatule - bezpiecznej, ciemnej, bez ruchu i dostępu powietrza - twoje serce ulegnie zmianie. Nie zostanie złamane; stanie się niemożliwe do złamania, niewzruszone, stracone na zawsze.   -Cztery Miłości, C.S. Levis-*",
      "Temat miłości poruszony  przeze mnie dzisiaj jest  tematem  niezwykle  obszernym. Zamieszczone  tutaj  osobiste  wnioski  zostały  opisane  jedynie  pokrótce i w dużym  uproszczeniu, mogą stanowić pewien punkt odniesienia do pracy nad wnikliwym przemyśleniem tematu. Mam nadzieję, że zachęcą Cię do dalszych poszukiwań.  Poniżej zamieszczam  listę  źródeł z jakich  korzystałam, może posłużą  również  Tobie:",
      "A. Damasio - Błąd Kartezjusza\nP. Curtaz - Miłość i inne sporty ekstremalne\nG.  Chapman -  5 języków miłości\nUniwersytet SWPS:  K.Popiołek - Trudne czasy dla bliskich związków\nUniwersytet SWPS:  M. Janus - Seks zaczyna się w głowie. O neurobiologii funkcjonowania seksualnego\nUniwersytet SWPS: M. Pozdał - Kobieca seksualność. Czy naprawdę istnieją oziębłe kobiety?\nC.S. Levis - Cztery Miłości\nG.T. Stanton - The Ring Makes All the Difference: The Hidden Consequences of Cohabitation and the Strong Benefits of Marriage\nNY Times: M. Jay - The Downside of Cohabiting Before Marriage\nJ. Eldredge - Dzikie serce. Tęsknoty męskiej duszy\nS. Eldredge, J. Eldredge  - Urzekająca\nD. DePierre - A brief history of oral sex\nBiblia  -  Hymn o miłości (1 Kor 13)"
    ],
    footerText: "",
    summary: "Czym jest miłość? Wszyscy o niej mówią, wszyscy o niej marzą, ale do tej pory nie doczekała się jednej i niezmiennej definicji… Dlaczego?",
    alt: "Odpoczynek autora na zboczu szlaku",
    flagWatermark: "26/07/2023 M.R.",
    image: goryMt,
    imageMin: goryMtMin,
    width: "1288",
    height: "859",
    widthMin: "632",
    heightMin: "474",
    link: "",
    link1: "",
    linkTitle: "",
    linkTitle1: "",
    tags: [
      "miłość",
      "zakochanie",
      "małżeństwo",
      "rodzina",
      "relacje",
      "związki"
    ],
    literature: [
      "A. Damasio - Błąd Kartezjusza",
      "P. Curtaz - Miłość i inne sporty ekstremalne",
      "G.  Chapman -  5 języków miłości",
      "Uniwersytet SWPS:  K.Popiołek - Trudne czasy dla bliskich związków",
      "Uniwersytet SWPS:  M. Janus - Seks zaczyna się w głowie. O neurobiologii funkcjonowania seksualnego",
      "Uniwersytet SWPS: M. Pozdał - Kobieca seksualność. Czy naprawdę istnieją oziębłe kobiety?",
      "C.S. Levis - Cztery Miłości",
      "G.T. Stanton - The Ring Makes All the Difference: The Hidden Consequences of Cohabitation and the Strong Benefits of Marriage",
      "NY Times: M. Jay - The Downside of Cohabiting Before Marriage",
      "J. Eldredge - Dzikie serce. Tęsknoty męskiej duszy",
      "S. Eldredge, J. Eldredge  - Urzekająca",
      "D. DePierre - A brief history of oral sex",
      "Biblia  -  Hymn o miłości (1 Kor 13)"
    ],
    flagColor: "flag-title-bright"
  },
  {
    id: 8,
    title: "Co warto czytać? Moje TOP3 książki",
    text: [
      "Co warto czytać? Bez wątpienia wszystko, co Cię interesuje. A gdyby decydować pomiędzy cokolwiek a nic zdecydowanie wybierz cokolwiek, gdyż każda wiedza jest lepsza niż jej brak. Jeżeli zaś ciekawi Cię, które książki wywarły na mnie największy wpływ/odbiły ślad w moim życiu zachęcam do sprawdzenia mojego TOP 3",
      "**Miejsce 3**.",
      "Obsadzenie najniższego stopnia podium sprawiło mi chyba najwięcej problemów. Ostatecznie miejsce trzecie zostało przyznane ex aeqo dwóm pozycjom:",
      "*Cesarz* - Ryszard Kapuściński \n *Rodzina Curie* - Denis Brian",
      "Cesarz to klasyka reportażu, majstersztyk Ryszarda Kapuścińskiego, który opisuje kulisy upadku dyktatury Hajlie Sellasie. Z jednej strony książka, do której długo się zbierałam i jeszcze dłużej ją czytałam, z drugiej dzieło wybitne opisujące w kunsztownej formie ludzkie nędze i mechanizmy działania. Cesarstwo w czasach schyłku to swoisty labirynt postaw, ludzkich zachowań. Czytając niejednokrotnie powtarzałam sobie: nie to jakaś ściema tak być nie mogło,  ludzie tak nie działają… Po kilku minutach refleksji nad poszczególnym fragmentem zmiana - postawy wprost z dworu Sellasie są obecne także u ludzi z  mojego szerszego otoczenia. Jaka ta książka jest prawdziwa… Z kolei Rodzina Curie  to biografia Marii, Piotra oraz ich córek. Czytasz biografię, ale czujesz jakbyś czytał powieść sensacyjną. Książka trzyma w napięciu i ujawnia mało znane (ależ jak znaczące) fakty z życia rodziny noblistów Curie. Po przeczytaniu tej książki wiem jedno -  Maria Curie to najwybitniejsza kobieta jakiej życiorys dane mi było poznać. Kobieta, żona, matka, nauczycielka, naukowiec, altruistka. Skromna, prosta, pracowita… Chciałabym być taką jak ona… chociażby w jednym procencie.",
      "**Miejsce 2**",
      "*Outliers: The Story of Success* - Malcolm Gladwell",
      "Przedstawiając Outliers  posłużę się cytatem ze Stevena Kinga: Życie jest fair. Wszyscy trzęsiemy się w brzuchu przez dziewięć miesięcy, a potem kości zostają rzucone. Niektórym wypadają dwie szóstki, innym, niestety dwie jedynki. Tak właśnie dzieje się na świecie. Malcolm Gladwell analizując czynniki  jakie zdecydowały o tym, że konkretnym ludziom dane było odnieść sukces w życiu zapuszcza się w te analizy bardzo głęboko, na przykład w to, w której części roku zostaliśmy urodzeni oraz kim byli nasi pra pra pra pra ojcowie i dowodzi zarazem, że do sukcesu nie wystarczy  tylko wyświechtany wrodzony talent i/lub ciężka praca. Książka dająca do myślenia.",
      "**Miejsce 1**",
      "*Człowiek w poszukiwaniu sensu  - Viktor Frankl*",
      "Austriacki psychiatra w obozie koncentracyjnym  -  po takim wstępie  miałam duże obawy czy warto zabierać się do tej książki. Po czasach liceum i polskiego podejścia do literatury obozowej miałam, delikatnie rzecz ujmując, lekką niechęć do tego typu tematyki. Książkę jednak  całe szczęście przeczytałam. Spostrzeżenia: można inaczej. Odnajdując sens  w naszym życiu wszystko nabiera nieco kolorów nawet szaro popiołowe niebo nad Auschwitz. Dla jasności dodam, że książka składa się z dwóch części: pierwsza to właśnie wspomnienia autora z obozu koncentracyjnego,  druga jest poświęcona logoterapii - czyli metody psychoterapii opracowanej przez Viktora Frankla. Obie części książki są ze sobą ściśle związane a samo przeczytanie książki może być dla nas jakąś formą terapii i stanowić punkt życiowej rewolucji. Szczerze polecam. Otwierająca książka."
    ],
    footerText: "",
    summary: " Co warto czytać? Bez wątpienia wszystko, co Cię interesuje. A gdyby decydować pomiędzy cokolwiek a nic zdecydowanie wybierz cokolwiek, gdyż każda wiedza jest lepsza niż jej brak. Jeżeli zaś ciekawi Cię, które książki wywarły na mnie największy wpływ/odbiły ślad w moim życiu zachęcam do sprawdzenia mojego TOP 3.",
    alt: "Co warto czytać? Moje TOP3 książki",
    flagWatermark: "26/07/2023 M.R.",
    image: biblioteczka,
    imageMin: biblioteczkaMin,
    width: "1920",
    height: "1440",
    widthMin: "632",
    heightMin: "474",
    link: "",
    link1: "",
    linkTitle: "",
    linkTitle1: "",
    tags: [
      "książki",
      "literatura",
      "reportaż",
      "wiedza",
      "top3",
      "wpływ",
      "Curie",
      "Frankl",
      "sukces",
      "Kapuściński"
    ],
    flagColor: "flag-title-dark"
  },
  {
    id: 9,
    title: "W poszukiwaniu transcendencji",
    text: [
      "Dwudziesty pierwszy wiek. Era ekranów, ledów, laserów. Intensyfikacja barw, 100% nasycenia kolorem. Photoshop. Perfekcja. Perspektywa. Opracowane w detalach zdjęcia. Niedoskonałości ukryte pod tonami pudru i markowym ciuchem. Zdjęcie odpowiednio wykadrowane, żeby przedstawiało idealny świat materii. Trawa pomalowana na zielono… Relacja tu - rolka tam. Nowe story, nowe bodźce.. Wszystko takie piękne, takie ładne, proste. Życie cyfrowe… życie, gdzie jedyna głębia to głębia kolorów ekranu ajfona.",
      "Czy świat oszalał? Czy w pogoni za dowartościowaniem się i rywalizacją z innymi w cyfrowo-materialnym świecie istnieje piękno, które jest  po prostu naturalne i niezbywalne, ale zagubione w natłoku bodźców?",
      "Od tysięcy lat człowiek różnych kultur, regionów i obyczajów poszukuje w życiu czegoś więcej. Rytuały, religie, święta, festiwale to przejaw tęsknoty za głębią. Piękno sztuki, piękno przyrody - drogowskazy, które w obliczu wydawać by się mogło cyfrowego zatracenia sprowadzają mnie z powrotem ku życiu.",
      "Od wczesnych młodzieńczych lat lubię wychodzić w nocy w góry. Jest to czas, w którym łapię zgubiony gdzieś w pośpiechu życia  kontakt z samą sobą oraz ze światem. Restartuję swój mózg, aby mógł poruszać się sprawniej i radzić sobie z wieloma bodźcami. Doświadczam nieopisywalnego, ale nie odda tego żadne, najpiękniejsze nawet  cyfrowe zdjęcie.",
      "*Z dziennika wyprawy po transcendencję…*",
      "*Piątek po ciężkim tygodniu w pracy, wracając do domu w tramwaju szybkie sprawdzenie pogody i lista zakupów. Wrócić ogarnąć mieszkanie. Spakować plecak. Koło 22.00 wybrać dokąd by tu wyjść. Szybkie sprawdzenie  czasu dojazdu na nawigacji, ustawienie budzika, do pobudki średnio 2h.*",
      "*Sobota, tuż po pólnocy: dzwonek budzika, ledwie zmrużyłam oko. Mąż robi herbatę do termosu. Ja półprzytomna wskakuję w ubrania.  Sprawdzenie czy wszystko mamy?  Wyruszamy. Najpierw dojazd, szukanie  bezpiecznego parkingu w  wąskich, krętych, ciemnych dróżkach. Ok, zaparkowane.  Niewyspanie daje się we znaki, ale czas goni. Ubieram plecak - jak zwykle ciężki, za ciężki - krzyczą plecy przeczołgane wielogodzinnym siedzeniem w pracy.*",
      "*W drogę. Ciemno, zimno i pod górę. Wśród drzew ciężko odnaleźć ledwo co przetartą ścieżkę. Po co się tak męczyć???  Drepczę powoli. Krok po kroku. Cel - nie zatrzymywać się w drodze. Wsłuchuję się w swój przyspieszony oddech. Wchodzimy coraz mocniej w las. Zanurzam się w ciszy. Wyłączam czołówkę, rozkoszuję się ciemnością. Kompletna pustka. Pierwszy postój gdzieś przy powalonym drzewie. Sprawdzenie trasy, sprawdzenie czasu. W górę. Do docelowego miejsca docieramy, gdy niebo robi się delikatnie różowe. Kompletna cisza. Tylko my, gwiazdy, i wielki świat.*",
      "*Gdy wysiłek ustaje organizm momentalnie się wychładza. Wrzucam więc na siebie wszytko co mam w plecaku, ale i tak jest zimno. Okrywam się szczelnie, próbując nie tracić ciepła. Siadam nieruchomo i zatapiam się spektakl. Myśli odpływają, oczy łapią szybko  pierwsze promienie słońca. Świat się budzi. Zmęczenie ustępuje. Niedoskonałości przestają doskwierać. Na twarzy pojawia się rozmarzenie. Łapię transcendencję.*",
      "*Czas na śniadanie. Dwudniowe bułki z kabanosami smakują wybornie. Łyczek kawy i powrót. Najpierw z góry, zaczynam czuć nogi. Szybki postój  przy samochodzie. Trzeba jakoś  ogarnąć ubłocone buty. Kierunek - dom. W międzyczasie postój przy jakimś markecie, żeby kupić coś na obiad.*",
      "*15.00 Docieramy do domu. Prysznic. Pranie. Drzemka.  Obiad. …*"
    ],
    footerText: "",
    summary: "Dwudziesty pierwszy wiek. Era ekranów, ledów, laserów. Intensyfikacja barw, 100% nasycenia kolorem. Photoshop. Perfekcja. Perspektywa. Opracowane w detalach zdjęcia. Niedoskonałości ukryte pod tonami pudru i markowym ciuchem. Zdjęcie odpowiednio wykadrowane, żeby przedstawiało idealny świat materii. Trawa pomalowana na zielono… Relacja tu - rolka tam. Nowe story, nowe bodźce.. Wszystko takie piękne, takie ładne, proste. Życie cyfrowe… życie, gdzie jedyna głębia to głębia kolorów ekranu ajfona.",
    alt: "Szczebel o świcie/M.Rośko",
    flagWatermark: "05/09/2023 M.R.",
    image: transcendencji,
    imageMin: transcendencjiMin,
    width: "1920",
    height: "1080",
    widthMin: "632",
    heightMin: "474",
    link: "",
    link1: "",
    linkTitle: "",
    linkTitle1: "",
    tags: [
      "nature",
      "natura",
      "naturalność",
      "niebo",
      "przyroda",
      "XXI",
      "materializm",
      "góry",
      "transcendencja",
      "sens",
      "inspiracje"
    ],
    flagColor: "flag-title-bright"
  },
  {
    id: 10,
    title: "Wielka cisza",
    text: [
      "Kończę intensywny dzień w pracy. Po natłoku spotkań, ustaleń i telefonów potrzebuję chwili wytchnienia. Krótki spacer ruchliwą ulicą i docieram na przystanek. Wchodzę do tramwaju, siadam w wygodnym miejscu, takim na walizki. Otwieram książkę. Czytam zdanie po zdaniu. Dwa siedzenia dalej trwa intensywna wymiana zdań między starszymi Panami. Zamiast treści książki do mojego mózgu docierają informacje o czyichś prywatnych sprawach typu: co zjadłem na śniadanie i po czym mam wzdęcia. Usiłuję się odciąć. Czytam zdanie raz, drugi, trzeci. Ile można o tych wzdęciach i śmierdzących stopach jeszcze? Wstaję i przesiadam się do drugiej części tramwaju. Względny spokój. Siadam, czytam. Tramwaj dociera do kolejnego przystanku. Wsiada młody mężczyzna z słuchawkami w uszach. Toczy jakąś biznesową konwersację przez telefon, ale jakby rozmawiał ze mną… ehh. Zamykam książkę. Byle wysiąść. Za chwilę donośliwy dzwonek tramwaju. Motorniczy zdenerwowany, bo ktoś zajechał mu drogę... Ryk silnika i pojazd sprzed tramwaju znika w tumanie kurzu. Po co te nerwy?  Przede mną panie komentują zaistniałą sytuację. Głośno i dobitnie. W końcu dojechałam, wysiadam. Już tak blisko domu. Idę przez park w akompaniamencie spalinowej kosiarki i dmuchawy. Nie jest to dobry akompaniament do przemyślenia co dziś jeszcze przede mną.  Po drodze, na klatce schodowej mijam sprzątaczkę z sąsiadką. Mam wrażenie, że panie licytują się na ilość wypowiedzianych w minucie słów. Wchodzę do mieszkania. Duszno, ale okna nie otworzę, bo akurat przed nim stoi sznur rechoczących samochodów a i sąsiad podkręcił coś na subwooferze, że aż ściany drżą …",
      "W ostatnich latach sporo się mówi o zanieczyszczeniach powietrza, wód, gleb. Uciążliwe, fakt. Ja natomiast coraz bardziej doświadczam zanieczyszczenia hałasem. Ilość bodźców, którą dostarczamy swojemu organizmowi produkując najrozmaitsze, nie pochodzące z natury dźwięki  jest przeogromna. NIe ma czasu odpocząć. Chodzimy przestymulowani a mimo to produkujemy wokół siebie coraz to więcej hałasu. Nasz mózg, żeby prawidłowo funkcjonować potrzebuje odpoczynku. Ciszy. Braku informacji do przetworzenia. Tymczasem mam wrażenie, że niektórych cisza przeraża. Są ludzie, którzy gadają, gadają, gadają, gadają. A jak zaschnie im od gadania w gardle to włączają TV albo uruchamiają  bezprzewodowy głośnik, ewentualnie znajdą inną, generującą dźwięki zabawkę.",
      "Ty również robisz wszystko, by zagłuszyć siebie  i wszystko dookoła? Nie chcesz usłyszeć swego wnętrza? Boisz się co tam odkryjesz? Zagłusza Cię świat? Nie obawiaj się. Wiedza to pierwszy krok do zdrowia. Zawalcz o ciszę.  Zawsze znajdziesz jakiś sposób, by pobyć sam ze sobą (dopuszczalnie z dźwiękami natury). Zatop się w ciszy  chociaż na godzinę. Sprawdź, czy potrafisz zamilknąć. Spróbuj usłyszeć, co w tym czasie mówi Twoje ciało, Twoje wnętrze. Może dostrzeżesz potrzeby, której przebijają się przez tą ciszę a które w codziennym życiu są skutecznie zagłuszane przez hałasujący świat. Zaopiekuj się sobą.",
      "Jest takie powiedzenie, że najgłośniej bije pusty dzwon. NIe chciałbyś chyba być postrzegany jako pustego? Jeżeli szukasz sposobu na wyciszenie to napełnij swoje wnętrze: wartościowa książka, ciekawe hobby, spacer, medytacja, nowa kuchnia. Wtedy pokochasz ciszę i będziesz jej pragnął. Cisza z kolei napełni Cię po brzegi obfitością, pozwoli przyswoić informacje, poukładać mętlik w Twojej głowie, uspokoi Twoje myśli, podkreśli wartość Ciebie jako części wszechświata. Twoje ciało poczuje się  po prostu lepiej a ludzie z Twojego otoczenia docenią Twoją obecność bardziej, niż gdybyś zarzucił ich tysiącem (często nieprzemyślanych, zwyczajnie głupich) słów."
    ],
    footerText: "",
    summary: "Kończę intensywny dzień w pracy. Po natłoku spotkań, ustaleń i telefonów potrzebuję chwili wytchnienia. Krótki spacer ruchliwą ulicą i docieram na przystanek. Wchodzę do tramwaju, siadam w wygodnym miejscu, takim na walizki. Otwieram książkę. Czytam zdanie po zdaniu. Dwa siedzenia dalej trwa intensywna wymiana zdań między starszymi Panami. Zamiast treści książki do mojego mózgu docierają informacje...",
    alt: "Wielka cisza/M.Rośko",
    flagWatermark: "18/04/2024 M.R.",
    image: wielkaCisza,
    imageMin: wielkaCiszaMin,
    width: "1920",
    height: "1080",
    widthMin: "632",
    heightMin: "474",
    link: "",
    link1: "",
    linkTitle: "",
    linkTitle1: "",
    tags: [
      "cisza",
      "hałas",
      "natura",
      "wypoczynek",
      "relaks"
    ],
    flagColor: "flag-title-bright"
  }
];

export default data;
